"""add expenses and monthly_goals tables

Revision ID: ab32c81d8481
Revises: 587bc20d2058
Create Date: 2026-04-04 22:57:56.161124

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab32c81d8481"
down_revision: Union[str, None] = "587bc20d2058"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=True),
        sa.Column("year_month", sa.String(length=7), nullable=True),
        sa.Column("receipt_id", sa.UUID(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint("amount_cents > 0", name="ck_expenses_amount_positive"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["family_id"], ["families.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_expenses_category", "expenses", ["category_id"], unique=False)
    op.create_index("idx_expenses_family", "expenses", ["family_id"], unique=False)
    op.create_index("idx_expenses_family_year_month", "expenses", ["family_id", "year_month"], unique=False)
    op.create_table(
        "monthly_goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("year_month", sa.String(length=7), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint("amount_cents > 0", name="ck_monthly_goals_amount_positive"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["family_id"], ["families.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "category_id", "year_month", name="uq_monthly_goals_family_category_month"),
    )
    op.create_index("idx_monthly_goals_family_year_month", "monthly_goals", ["family_id", "year_month"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_monthly_goals_family_year_month", table_name="monthly_goals")
    op.drop_table("monthly_goals")
    op.drop_index("idx_expenses_family_year_month", table_name="expenses")
    op.drop_index("idx_expenses_family", table_name="expenses")
    op.drop_index("idx_expenses_category", table_name="expenses")
    op.drop_table("expenses")
    # ### end Alembic commands ###
