"""create users and refresh_token_blacklist tables

Revision ID: d2457cd3ba1a
Revises: e508f2e08a06
Create Date: 2026-03-23 15:04:14.690504

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "d2457cd3ba1a"  # pragma: allowlist secret
down_revision: Union[str, None] = "e508f2e08a06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("google_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_login_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_id"),
    )
    op.create_table(
        "refresh_token_blacklist",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    op.create_index("ix_refresh_token_blacklist_expires_at", "refresh_token_blacklist", ["expires_at"], unique=False)
    op.create_index("ix_refresh_token_blacklist_jti", "refresh_token_blacklist", ["jti"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_refresh_token_blacklist_jti", table_name="refresh_token_blacklist")
    op.drop_index("ix_refresh_token_blacklist_expires_at", table_name="refresh_token_blacklist")
    op.drop_table("refresh_token_blacklist")
    op.drop_table("users")
    # ### end Alembic commands ###
